### ISSUE TITLE
animated background

### ISSUE THREAD

**Issue by 14easthopel** [UTCSheffield/RusheyMeadow#5]
https://codepen.io/anon/pen/ELzoLj
https://www.fg-a.com/animated_backgrounds2.html
https://vincentgarreau.com/particles.js/

**Comment by 14easthopel** [comment]
https://codepen.io/anon/pen/ELzoLj

**Comment by tomfairey** [comment]
They want an animated background to lol up when the questions are submitted (due to distractions), not the whole time like my prototype

**Comment by 14easthopel** [comment]
this is ny area :)
plz no reply

**Comment by 14allenc** [comment]
hi
