### ISSUE TITLE
Questions written and translated with pictures for the picture questions.

### ISSUE THREAD

**Issue by mr-eggleton** [UTCSheffield/RusheyMeadow#6]

**Comment by 14pettj** [comment]
- [ ] Do you enjoy Rushey Meadow?
- [ ] Do the staff help you?
- [ ] What would you like to do today?
- [ ] What food do you like?
- [ ] What activities do you like?

**Comment by mr-eggleton** [comment]
Attached is @robtweddle 's take on the sentences, Can we get this in before Thursday?

[rob comms.docx](https://github.com/UTCSheffield/RusheyMeadow/files/2111453/rob.comms.docx)

**Comment by mr-eggleton** [comment]
The standard way is aligned to the words and above.

**Comment by stretchyboy** [comment]
Now we need to get the auto PEc symboling to come from the database.
