### ISSUE TITLE
wireframe +

### ISSUE THREAD

**Issue by mr-eggleton** [UTCSheffield/RusheyMeadow#8]

**Comment by 14zrobczynskij** [comment]
https://www.draw.io/

**Comment by 14zrobczynskij** [comment]
https://www.fluidui.com (1 project max, up to 10 pages per project)

**Comment by 14zrobczynskij** [comment]
https://www.fluidui.com/editor/live/preview/cF9MM2VtbXF3ZzVLaWhRTIVUVnIER2h6aW9Xb2JHMVhHOQ==

**Comment by 14zrobczynskij** [comment]
https://www.fluidui.com/editor/live/link/8Py1zxAMiD2uHUZmJLS2rXHAqKJ0JnSI2RaNrSRsIJghNklqpmQRgMHpQiCexoRf

should work without logging in now
