### ISSUE TITLE
Sound for yes and no answers (could be other noise feedback)

### ISSUE THREAD

**Issue by 14allenc** [UTCSheffield/RusheyMeadow#9]

**Comment by mr-eggleton** [comment]
Remember all answers need positive noises, and there shouldn't be any way to know what sound will trigger when a particular button is pressed  so we don't form positive  or negative associations that affect the answers we are getting from the children.

**Comment by mr-eggleton** [comment]
@14allenc have you got those links from freesound.org that you could drop into this issues comments to get some feedback from the group?  Thank you.

**Comment by mr-eggleton** [comment]
Collaborative Editor  https://glitch.com/edit/#!/join/395dd956-1468-45bf-97fc-1200d569f616

**Comment by mr-eggleton** [comment]
@14zrobczynskij committed code that's does this yesterday. 
Please review.
I think some of the sounds are very long. But the code seems to work
